"""Add notifications_enabled column to users table

Revision ID: 0763f6c96f0d
Revises: 81347d3ad7ab
Create Date: 2025-09-18 13:15:43.739114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0763f6c96f0d'
down_revision: Union[str, None] = '81347d3ad7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with a default value for existing users
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # Remove the server default after adding the column
    op.alter_column('users', 'notifications_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
