"""Remove_college_name_and_role

Revision ID: 123ecc4d436a
Revises: 573c223863a6
Create Date: 2025-08-19 12:35:42.252003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '123ecc4d436a'
down_revision: Union[str, None] = '573c223863a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep the unique constraint on email
    op.drop_column('users', 'role')
    op.drop_column('users', 'college_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', postgresql.ENUM('STUDENT', 'TEACHER', name='userrole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
