"""Initial migration

Revision ID: 19f27a94658c
Revises: 
Create Date: 2025-08-21 21:58:12.023903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f27a94658c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type only if it doesn't exist
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'otppurpose'")
    ).fetchone()
    if not result:
        op.execute(sa.text("CREATE TYPE otppurpose AS ENUM ('verification', 'forgot_password')"))
    
    op.create_table('admins',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_admins_aid'), 'admins', ['aid'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fname', sa.String(length=128), nullable=False),
    sa.Column('lname', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    # Create user_otps table using raw SQL to avoid enum creation issues
    op.execute(sa.text("""
        CREATE TABLE user_otps (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL,
            otp_code VARCHAR(10) NOT NULL,
            expires_at TIMESTAMP NOT NULL,
            is_used BOOLEAN NOT NULL,
            for_purpose otppurpose NOT NULL,
            created_at TIMESTAMP NOT NULL,
            attempts INTEGER NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(uid)
        )
    """))
    op.create_index(op.f('ix_user_otps_for_purpose'), 'user_otps', ['for_purpose'], unique=False)
    op.create_index(op.f('ix_user_otps_id'), 'user_otps', ['id'], unique=False)
    op.create_index(op.f('ix_user_otps_user_id'), 'user_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_otps_user_id'), table_name='user_otps')
    op.drop_index(op.f('ix_user_otps_id'), table_name='user_otps')
    op.drop_index(op.f('ix_user_otps_for_purpose'), table_name='user_otps')
    op.execute(sa.text("DROP TABLE user_otps"))
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_aid'), table_name='admins')
    op.drop_table('admins')
    
    # Drop enum type only if it exists and no other tables are using it
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'otppurpose'")
    ).fetchone()
    if result:
        # Check if any tables are using this enum
        usage_check = connection.execute(
            sa.text("SELECT 1 FROM information_schema.columns WHERE udt_name = 'otppurpose'")
        ).fetchone()
        if not usage_check:
            op.execute(sa.text("DROP TYPE otppurpose"))
    
    # ### end Alembic commands ###
