"""Add sequential analysis fields to archive

Revision ID: 27ebf0fab472
Revises: add_degree_program_column
Create Date: 2025-09-15 10:26:58.229688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ebf0fab472'
down_revision: Union[str, None] = 'add_degree_program_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('abstract_results', sa.JSON(), nullable=True))
    op.add_column('archives', sa.Column('abstract_summary', sa.JSON(), nullable=True))
    op.add_column('archives', sa.Column('acknowledgement_results', sa.JSON(), nullable=True))
    op.add_column('archives', sa.Column('acknowledgement_summary', sa.JSON(), nullable=True))
    op.add_column('archives', sa.Column('abstract_status', sa.String(length=50), nullable=True))
    op.add_column('archives', sa.Column('acknowledgement_status', sa.String(length=50), nullable=True))
    op.add_column('archives', sa.Column('abstract_error', sa.Text(), nullable=True))
    op.add_column('archives', sa.Column('acknowledgement_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archives', 'acknowledgement_error')
    op.drop_column('archives', 'abstract_error')
    op.drop_column('archives', 'acknowledgement_status')
    op.drop_column('archives', 'abstract_status')
    op.drop_column('archives', 'acknowledgement_summary')
    op.drop_column('archives', 'acknowledgement_results')
    op.drop_column('archives', 'abstract_summary')
    op.drop_column('archives', 'abstract_results')
    # ### end Alembic commands ###
