"""Initial migration - create all tables

Revision ID: 408a15036b99
Revises: 
Create Date: 2025-09-18 13:36:27.480225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408a15036b99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types if they don't exist
    connection = op.get_bind()
    
    # Create enum types if they don't exist
    op.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE issuestatusenum AS ENUM ('pending', 'inprogress', 'resolved', 'closed');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    op.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE otppurpose AS ENUM ('verification', 'forgot_password');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    op.create_table('admins',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_admins_aid'), 'admins', ['aid'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('configs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('smtp_server', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.String(length=10), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configs_id'), 'configs', ['id'], unique=False)
    op.create_table('faqs',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_index(op.f('ix_faqs_fid'), 'faqs', ['fid'], unique=False)
    op.create_index(op.f('ix_faqs_priority'), 'faqs', ['priority'], unique=False)
    op.create_index(op.f('ix_faqs_question'), 'faqs', ['question'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fname', sa.String(length=128), nullable=False),
    sa.Column('lname', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.Column('abstract_results', sa.JSON(), nullable=True),
    sa.Column('abstract_summary', sa.JSON(), nullable=True),
    sa.Column('acknowledgement_results', sa.JSON(), nullable=True),
    sa.Column('acknowledgement_summary', sa.JSON(), nullable=True),
    sa.Column('abstract_status', sa.String(length=50), nullable=True),
    sa.Column('acknowledgement_status', sa.String(length=50), nullable=True),
    sa.Column('abstract_error', sa.Text(), nullable=True),
    sa.Column('acknowledgement_error', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archives_id'), 'archives', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('user_otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('for_purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_otps_for_purpose'), 'user_otps', ['for_purpose'], unique=False)
    op.create_index(op.f('ix_user_otps_id'), 'user_otps', ['id'], unique=False)
    op.create_index(op.f('ix_user_otps_user_id'), 'user_otps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_otps_user_id'), table_name='user_otps')
    op.drop_index(op.f('ix_user_otps_id'), table_name='user_otps')
    op.drop_index(op.f('ix_user_otps_for_purpose'), table_name='user_otps')
    op.drop_table('user_otps')
    op.drop_table('issues')
    op.drop_index(op.f('ix_archives_id'), table_name='archives')
    op.drop_table('archives')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_faqs_question'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_priority'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_fid'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_configs_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_aid'), table_name='admins')
    op.drop_table('admins')
    
    # Drop enum types if they exist
    connection = op.get_bind()
    
    # Check if otppurpose exists and drop it
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'otppurpose'")
    ).fetchone()
    if result:
        op.execute(sa.text("DROP TYPE IF EXISTS otppurpose"))
    
    # Check if issuestatusenum exists and drop it
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'issuestatusenum'")
    ).fetchone()
    if result:
        op.execute(sa.text("DROP TYPE IF EXISTS issuestatusenum"))
    
    # ### end Alembic commands ###
