"""add_phone_number_to_users

Revision ID: 9e6b6c399610
Revises: edfed3ed4511
Create Date: 2025-08-19 13:51:00.297417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6b6c399610'
down_revision: Union[str, None] = 'edfed3ed4511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # Don't drop the email unique constraint
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't recreate the email unique constraint as we're not dropping it in upgrade
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
