"""create FAQ table with priority colum

Revision ID: bbd0ff386da8
Revises: 840f4cab7231
Create Date: 2025-08-22 12:54:33.983947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd0ff386da8'
down_revision: Union[str, None] = '840f4cab7231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('priority', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_faqs_priority'), 'faqs', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faqs_priority'), table_name='faqs')
    op.drop_column('faqs', 'priority')
    # ### end Alembic commands ###
