"""update_archive_table_with_analysis_fields

Revision ID: d6b3e01469db
Revises: 1a68ffba1288
Create Date: 2025-08-21 16:06:51.591692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6b3e01469db'
down_revision: Union[str, None] = '1a68ffba1288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('user_id', sa.Integer(), nullable=True))  # Made nullable first
    op.add_column('archives', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('archives', sa.Column('analysis_content', sa.Text(), nullable=True))
    op.add_column('archives', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('archives', sa.Column('processing_status', sa.String(length=50), nullable=True))
    op.add_column('archives', sa.Column('error_message', sa.Text(), nullable=True))
    
    # Handle TEXT to JSON conversion with USING clause, set empty arrays for null values
    op.execute("ALTER TABLE archives ALTER COLUMN suggestions TYPE JSON USING CASE WHEN suggestions IS NULL OR suggestions = '' THEN '[]'::JSON ELSE suggestions::JSON END")
    op.execute("ALTER TABLE archives ALTER COLUMN warnings TYPE JSON USING CASE WHEN warnings IS NULL OR warnings = '' THEN '[]'::JSON ELSE warnings::JSON END")
    op.execute("ALTER TABLE archives ALTER COLUMN errors TYPE JSON USING CASE WHEN errors IS NULL OR errors = '' THEN '[]'::JSON ELSE errors::JSON END")
    
    op.alter_column('archives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('archives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_archives_uid', table_name='archives')
    op.drop_constraint('archives_uid_fkey', 'archives', type_='foreignkey')
    op.create_foreign_key(None, 'archives', 'users', ['user_id'], ['uid'])
    op.drop_column('archives', 'uid')
    
    # Now make user_id not nullable after the foreign key is set up
    op.alter_column('archives', 'user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'archives', type_='foreignkey')
    op.create_foreign_key('archives_uid_fkey', 'archives', 'users', ['uid'], ['uid'], ondelete='CASCADE')
    op.create_index('ix_archives_uid', 'archives', ['uid'], unique=False)
    op.alter_column('archives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('archives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('archives', 'errors',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('archives', 'warnings',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('archives', 'suggestions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('archives', 'error_message')
    op.drop_column('archives', 'processing_status')
    op.drop_column('archives', 'file_size')
    op.drop_column('archives', 'analysis_content')
    op.drop_column('archives', 'file_path')
    op.drop_column('archives', 'user_id')
    # ### end Alembic commands ###
