"""Replace_name_with_fname_lname

Revision ID: edfed3ed4511
Revises: 123ecc4d436a
Create Date: 2025-08-19 12:38:09.347628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfed3ed4511'
down_revision: Union[str, None] = '123ecc4d436a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with nullable=True initially
    op.add_column('users', sa.Column('fname', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(length=128), nullable=True))
    
    # Data migration: Split name into fname and lname
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE users 
        SET 
            fname = SPLIT_PART(name, ' ', 1),
            lname = CASE
                WHEN POSITION(' ' IN name) > 0 THEN SUBSTRING(name FROM POSITION(' ' IN name) + 1)
                ELSE ''
            END
    """))
    
    # Now make the new columns non-nullable
    op.alter_column('users', 'fname', nullable=False)
    op.alter_column('users', 'lname', nullable=False)
    
    # Drop the old name column
    op.drop_column('users', 'name')
    
    # Check if the constraint exists before creating it
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'users_email_key'
    """))
    if result.fetchone() is None:
        op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add name column as nullable first
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    
    # Data migration: Combine fname and lname into name
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE users 
        SET name = CONCAT(fname, ' ', lname)
    """))
    
    # Make name non-nullable
    op.alter_column('users', 'name', nullable=False)
    
    # Drop the new columns
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
