"""create Issues table

Revision ID: fe2d3feda58d
Revises: bbd0ff386da8
Create Date: 2025-08-22 16:11:57.080389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2d3feda58d'
down_revision: Union[str, None] = 'bbd0ff386da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type only if it doesn't exist
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'issuestatusenum'")
    ).fetchone()
    if not result:
        op.execute(sa.text("CREATE TYPE issuestatusenum AS ENUM ('pending', 'inprogress', 'resolved', 'closed')"))
    
    # Create issues table using raw SQL to avoid enum creation issues
    op.execute(sa.text("""
        CREATE TABLE issues (
            issue_id UUID PRIMARY KEY,
            uid INTEGER NOT NULL,
            title VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            image VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
            status issuestatusenum NOT NULL,
            FOREIGN KEY (uid) REFERENCES users(uid)
        )
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP TABLE issues"))
    
    # Drop enum type only if it exists and no other tables are using it
    connection = op.get_bind()
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'issuestatusenum'")
    ).fetchone()
    if result:
        # Check if any tables are using this enum
        usage_check = connection.execute(
            sa.text("SELECT 1 FROM information_schema.columns WHERE udt_name = 'issuestatusenum'")
        ).fetchone()
        if not usage_check:
            op.execute(sa.text("DROP TYPE issuestatusenum"))
    
    # ### end Alembic commands ###
